user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    set_real_ip_from 172.16.0.0/12;
    real_ip_header X-Forwarded-For;
    real_ip_recursive on;

    log_format json_log escape=json
        '{'
            '"source_ip":"$remote_addr",'
            '"timestamp":"$time_iso8601",'
            '"method":"$request_method",'
            '"path":"$request_uri",'
            '"status":$status,'
            '"response_size":$body_bytes_sent,'
            '"http_host":"$host",'
            '"user_agent":"$http_user_agent"'
        '}';

    access_log /var/log/nginx/hng-access.log json_log;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        client_max_body_size 512M;

        resolver 127.0.0.11 valid=30s;
        set $upstream http://nextcloud:80;

        location / {
            proxy_pass $upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 300s;
        }
        location /loaderio-4ab574b868fa222dee91b917a8bc1b85.txt {
            return 200 "loaderio-4ab574b868fa222dee91b917a8bc1b85";
            add_header Content-Type text/plain;
}
    }
}
